//
// Created by Dawood Parhiar on 10/04/2023.
//

#ifndef BUGLIFE_CA3_DAWOODPARHIAR_GD2_BOARD_H
#define BUGLIFE_CA3_DAWOODPARHIAR_GD2_BOARD_H


class Board {

};


#endif //BUGLIFE_CA3_DAWOODPARHIAR_GD2_BOARD_H
