//
// Created by Dawood Parhiar on 20/04/2023.
//

#ifndef BUGLIFE_CA3_DAWOODPARHIAR_GD2_CRAWLER_H
#define BUGLIFE_CA3_DAWOODPARHIAR_GD2_CRAWLER_H


class Crawler {

};


#endif //BUGLIFE_CA3_DAWOODPARHIAR_GD2_CRAWLER_H
