//
// Created by Dawood Parhiar on 20/04/2023.
//

#ifndef BUGLIFE_CA3_DAWOODPARHIAR_GD2_HOPPER_H
#define BUGLIFE_CA3_DAWOODPARHIAR_GD2_HOPPER_H


class Hopper {

};


#endif //BUGLIFE_CA3_DAWOODPARHIAR_GD2_HOPPER_H
